const bcworkshop = new require("bcworkshop");

const passive = new bcworkshop.Passive("Passive", function check(acted, victim, message){
    return false;
  }, function passed(acted, victim, message){
    victim.hp = victim.hp - 28;
    let embed = new Discord.MessageEmbed()
    .setTitle(`Uh oh, [${acted.username}] ${acted.bey.bbname || acted.bey.name} tried to use it's passive ability but it was not set up properly. 28 damage dealt.`)
    .setDescription("Please report this at the support server.")
    .setColor("#551a8b");
    message.channel.createMessage({embed: embed});
  }, 180);

const special = new bcworkshop.Special("Special", function req(acted, victim, logger){return acted.sp > 3}, function special(acted, victim, message){
    
	
	 let before = victim.hp;
    let base = 50;
    let plus = 0;
    for(var i = 0; i < acted.lvl; i++){
       plus = plus + 0.3; 
	   //+0.1 every level which means 1 more damage every 10 levels
    }
    let dmg = base + plus;
    victim.hp = victim.hp - dmg;
    let after = victim.hp;
    let diff = before - after;
	victim.atk = Math.round((victim.atk/100)*65);
    acted.stamina = acted.stamina - 1;
    //Change "victim.hp = victim.hp - 123" to "victim.hp = victim.hp - <damage number>. This and the line below can be removed if the special move does not deal any damage.
    //For more options check the README.md
    
    //Make sure to change the "Name", "Special Name" and damage dealt below.
    let embed = new Discord.MessageEmbed()
	.setTitle(`[${acted.username}] Dragoon Storm used **Storm Attack**.`)
	.setDescription(`Dragoon used the wind flowing through it's Wing disc, and the incredible spin velocity generated by it's Xtreme driver to create a huge tornado around itself that reduced damage by 35%. The tornado's vacuum sucked in the opponent afterwards, spitting them out into the air for ${diff} damage. Dragoon lost 1 stamina due to the strain on it's spin velocity.`)
    .setColor("#551a8b");
    
    message.channel.createMessage({embed: embed});
  });

const DragoonStorm = new bcworkshop.Beyblade({name: "Dragoon Storm", type: "Attack", imageLink: "https://vignette.wikia.nocookie.net/beyblade/images/e/ec/Bey%2C_Burst_Dragoon_S_W.X_%28Takara_Tomy%29.png/revision/latest?cb=20200327123934"})
.attachPassive(passive)
.attachSpecial(special)
.setDefaultSD("RIGHT")
.setSDChangable(false);

module.exports = DragoonStorm;